# Generated by Django 5.0.6 on 2024-05-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_delete_newuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='depart',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='func',
            new_name='function',
        ),
    ]
