# Generated by Django 5.0.6 on 2024-05-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=200)),
                ('field2', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='api.form'),
        ),
    ]
