# Generated by Django 5.0.6 on 2024-05-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_form_avaliacao_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='field1',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='field2',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
