# Generated by Django 5.0.6 on 2024-05-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_form_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='field1',
        ),
        migrations.RemoveField(
            model_name='form',
            name='field2',
        ),
        migrations.AddField(
            model_name='form',
            name='assiduidade_in',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='assiduidade_ju',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='conhecimento',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='disponiblidade',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='produtividade',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='responsabilidade',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
