# Generated by Django 5.0.6 on 2024-05-16 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_form_field1_remove_form_field2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_recebidas', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_dadas', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='form',
            name='assiduidade_in',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='assiduidade_ju',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='conhecimento',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='disponiblidade',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='produtividade',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='responsabilidade',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
